sonar.organization=steam-ducks
sonar.projectKey=sca-server
sonar.projectName=sca-server

sonar.sources=.

sonar.exclusions=*/migrations/,/tests/,/_pycache_/,/.pyc

sonar.python.coverage.reportPaths=coverage.xml

sonar.sourceEncoding=UTF-8

sonar.host.url=https://sonarcloud.io