sonar.organization=steam-ducks
sonar.projectKey=Steam-Ducks_sca-server

sonar.sources=.
sonar.exclusions=**/migrations/**,**/tests/**,**/__pycache__/**,**/*.pyc
sonar.python.coverage.reportPaths=coverage.xml