global:
  scrape_interval: 15s
  evaluation_interval: 15s

remote_write:
  - url: https://prometheus-prod-40-prod-sa-east-1.grafana.net/api/prom/push
    basic_auth:
      username: '3046984'
      password: 'GRAFANA_CLOUD_TOKEN_PLACEHOLDER'

rule_files:
  - "alerts.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets: ["alertmanager:9093"]

scrape_configs:
  - job_name: 'sca_prod'
    metrics_path: /metrics
    static_configs:
      - targets: ['143.198.2.189:8000']

  - job_name: 'sca_staging'
    metrics_path: /metrics
    static_configs:
      - targets: ['143.198.2.189:8001']

  - job_name: 'postgresql'
    static_configs:
      - targets: ['postgres-exporter:9187']

  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']

