# Generated by Django 5.1.1 on 2026-03-31 23:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sca_data", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SilverComprasProjeto",
            fields=[
                ("id", models.BigIntegerField(primary_key=True, serialize=False)),
                ("valor_alocado", models.FloatField(blank=True, null=True)),
                ("silver_ingested_at", models.DateTimeField()),
            ],
            options={
                "db_table": 'silver"."compras_projeto',
            },
        ),
        migrations.CreateModel(
            name="SilverEmpenhoMaterial",
            fields=[
                ("id", models.BigIntegerField(primary_key=True, serialize=False)),
                ("quantidade_empenhada", models.BigIntegerField()),
                ("data_empenho", models.DateField(blank=True, null=True)),
                ("silver_ingested_at", models.DateTimeField()),
            ],
            options={
                "db_table": 'silver"."empenho_materiais',
            },
        ),
        migrations.CreateModel(
            name="SilverEstoqueMateriaisProjeto",
            fields=[
                ("id", models.BigIntegerField(primary_key=True, serialize=False)),
                ("quantidade", models.BigIntegerField()),
                (
                    "localizacao",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("silver_ingested_at", models.DateTimeField()),
            ],
            options={
                "db_table": 'silver"."estoque_materiais_projeto',
            },
        ),
        migrations.CreateModel(
            name="SilverFornecedor",
            fields=[
                ("id", models.BigIntegerField(primary_key=True, serialize=False)),
                ("codigo_fornecedor", models.CharField(max_length=50)),
                (
                    "razao_social",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("cidade", models.CharField(blank=True, max_length=100, null=True)),
                ("estado", models.CharField(blank=True, max_length=2, null=True)),
                ("categoria", models.CharField(blank=True, max_length=100, null=True)),
                ("status", models.CharField(blank=True, max_length=50, null=True)),
                ("silver_ingested_at", models.DateTimeField()),
            ],
            options={
                "db_table": 'silver"."fornecedores',
            },
        ),
        migrations.CreateModel(
            name="SilverMaterial",
            fields=[
                ("id", models.BigIntegerField(primary_key=True, serialize=False)),
                ("codigo_material", models.CharField(max_length=50)),
                ("descricao", models.CharField(blank=True, max_length=100, null=True)),
                ("categoria", models.CharField(blank=True, max_length=100, null=True)),
                ("fabricante", models.CharField(blank=True, max_length=100, null=True)),
                ("custo_estimado", models.FloatField(blank=True, null=True)),
                ("status", models.CharField(blank=True, max_length=50, null=True)),
                ("silver_ingested_at", models.DateTimeField()),
            ],
            options={
                "db_table": 'silver"."materiais',
            },
        ),
        migrations.CreateModel(
            name="SilverPedidoCompra",
            fields=[
                ("id", models.BigIntegerField(primary_key=True, serialize=False)),
                ("numero_pedido", models.CharField(max_length=50)),
                ("data_pedido", models.DateField(blank=True, null=True)),
                ("data_previsao_entrega", models.DateField(blank=True, null=True)),
                ("valor_total", models.FloatField(blank=True, null=True)),
                ("status", models.CharField(blank=True, max_length=50, null=True)),
                ("silver_ingested_at", models.DateTimeField()),
                (
                    "fornecedor",
                    models.ForeignKey(
                        db_column="fornecedor_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="sca_data.silverfornecedor",
                    ),
                ),
            ],
            options={
                "db_table": 'silver"."pedidos_compra',
            },
        ),
        migrations.CreateModel(
            name="SilverPrograma",
            fields=[
                ("id", models.BigIntegerField(primary_key=True, serialize=False)),
                ("codigo_programa", models.CharField(max_length=100)),
                ("nome_programa", models.CharField(max_length=100)),
                (
                    "gerente_programa",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "gerente_tecnico",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("data_inicio", models.DateField(blank=True, null=True)),
                ("data_fim_prevista", models.DateField(blank=True, null=True)),
                ("status", models.CharField(blank=True, max_length=50, null=True)),
                ("silver_ingested_at", models.DateTimeField()),
            ],
            options={
                "db_table": 'silver"."programas',
            },
        ),
        migrations.CreateModel(
            name="SilverProjeto",
            fields=[
                ("id", models.BigIntegerField(primary_key=True, serialize=False)),
                ("codigo_projeto", models.CharField(max_length=50)),
                (
                    "nome_projeto",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "responsavel",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("custo_hora", models.FloatField(blank=True, null=True)),
                ("data_inicio", models.DateField(blank=True, null=True)),
                ("data_fim_prevista", models.DateField(blank=True, null=True)),
                ("status", models.CharField(blank=True, max_length=50, null=True)),
                ("silver_ingested_at", models.DateTimeField()),
                (
                    "programa",
                    models.ForeignKey(
                        blank=True,
                        db_column="programa_id",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="projetos",
                        to="sca_data.silverprograma",
                    ),
                ),
            ],
            options={
                "db_table": 'silver"."projetos',
            },
        ),
        migrations.CreateModel(
            name="SilverSolicitacaoCompra",
            fields=[
                ("id", models.BigIntegerField(primary_key=True, serialize=False)),
                ("numero_solicitacao", models.CharField(max_length=50)),
                ("quantidade", models.BigIntegerField()),
                ("data_solicitacao", models.DateField(blank=True, null=True)),
                ("prioridade", models.CharField(blank=True, max_length=50, null=True)),
                ("status", models.CharField(blank=True, max_length=50, null=True)),
                ("silver_ingested_at", models.DateTimeField()),
                (
                    "material",
                    models.ForeignKey(
                        db_column="material_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="sca_data.silvermaterial",
                    ),
                ),
                (
                    "projeto",
                    models.ForeignKey(
                        db_column="projeto_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="sca_data.silverprojeto",
                    ),
                ),
            ],
            options={
                "db_table": 'silver"."solicitacoes_compra',
            },
        ),
        migrations.CreateModel(
            name="SilverTarefaProjeto",
            fields=[
                ("id", models.BigIntegerField(primary_key=True, serialize=False)),
                ("codigo_tarefa", models.CharField(max_length=50)),
                ("titulo", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "responsavel",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("estimativa_horas", models.IntegerField(blank=True, null=True)),
                ("data_inicio", models.DateField(blank=True, null=True)),
                ("data_fim_prevista", models.DateField(blank=True, null=True)),
                ("status", models.CharField(blank=True, max_length=50, null=True)),
                ("silver_ingested_at", models.DateTimeField()),
                (
                    "projeto",
                    models.ForeignKey(
                        db_column="projeto_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="tarefas",
                        to="sca_data.silverprojeto",
                    ),
                ),
            ],
            options={
                "db_table": 'silver"."tarefas_projeto',
            },
        ),
        migrations.CreateModel(
            name="SilverTempoTarefa",
            fields=[
                ("id", models.BigIntegerField(primary_key=True, serialize=False)),
                ("usuario", models.CharField(blank=True, max_length=100, null=True)),
                ("data", models.DateField()),
                ("horas_trabalhadas", models.FloatField()),
                ("silver_ingested_at", models.DateTimeField()),
                (
                    "tarefa",
                    models.ForeignKey(
                        db_column="tarefa_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="tempos",
                        to="sca_data.silvertarefaprojeto",
                    ),
                ),
            ],
            options={
                "db_table": 'silver"."tempo_tarefas',
            },
        ),
        migrations.DeleteModel(
            name="User",
        ),
        migrations.AddField(
            model_name="silverestoquemateriaisprojeto",
            name="material",
            field=models.ForeignKey(
                db_column="material_id",
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="sca_data.silvermaterial",
            ),
        ),
        migrations.AddField(
            model_name="silverempenhomaterial",
            name="material",
            field=models.ForeignKey(
                db_column="material_id",
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="sca_data.silvermaterial",
            ),
        ),
        migrations.AddField(
            model_name="silvercomprasprojeto",
            name="pedido_compra",
            field=models.ForeignKey(
                db_column="pedido_compra_id",
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="sca_data.silverpedidocompra",
            ),
        ),
        migrations.AddField(
            model_name="silverestoquemateriaisprojeto",
            name="projeto",
            field=models.ForeignKey(
                db_column="projeto_id",
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="sca_data.silverprojeto",
            ),
        ),
        migrations.AddField(
            model_name="silverempenhomaterial",
            name="projeto",
            field=models.ForeignKey(
                db_column="projeto_id",
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="sca_data.silverprojeto",
            ),
        ),
        migrations.AddField(
            model_name="silvercomprasprojeto",
            name="projeto",
            field=models.ForeignKey(
                db_column="projeto_id",
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="sca_data.silverprojeto",
            ),
        ),
        migrations.AddField(
            model_name="silverpedidocompra",
            name="solicitacao",
            field=models.ForeignKey(
                blank=True,
                db_column="solicitacao_id",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="sca_data.silversolicitacaocompra",
            ),
        ),
    ]
