# Generated by Django 5.1.1 on 2026-04-18 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sca_data", "0001_silver_schema"),
    ]

    operations = [
        migrations.AlterField(
            model_name="silvercomprasprojeto",
            name="silver_ingested_at",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="silverempenhomaterial",
            name="silver_ingested_at",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="silverestoquemateriaisprojeto",
            name="silver_ingested_at",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="silverfornecedor",
            name="silver_ingested_at",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="silvermaterial",
            name="silver_ingested_at",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="silverpedidocompra",
            name="silver_ingested_at",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="silverprograma",
            name="silver_ingested_at",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="silverprojeto",
            name="silver_ingested_at",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="silversolicitacaocompra",
            name="silver_ingested_at",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="silvertarefaprojeto",
            name="silver_ingested_at",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="silvertempotarefa",
            name="silver_ingested_at",
            field=models.DateTimeField(),
        ),
    ]
