# Generated by Django 5.1.1 on 2026-04-24 01:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sca_data", "0003_gold_indicadores_materiais"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditExecutionLog",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("run_id", models.UUIDField()),
                ("operation", models.CharField(max_length=20)),
                ("status", models.CharField(max_length=20)),
                (
                    "table_schema",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("table_name", models.CharField(blank=True, max_length=100, null=True)),
                ("affected_rows", models.IntegerField(blank=True, null=True)),
                ("started_at", models.DateTimeField()),
                ("finalized_at", models.DateTimeField(blank=True, null=True)),
                ("operation_duration", models.IntegerField(blank=True, null=True)),
                ("operation_metadata", models.JSONField(blank=True, null=True)),
            ],
            options={
                "db_table": 'audit"."execution_logs',
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="GoldCosts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateTimeField(blank=True, null=True)),
                (
                    "nome_programa",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "gerente_programa",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "nome_projeto",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "responsavel_projeto",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("custo", models.FloatField(blank=True, null=True)),
                ("gold_updated_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": 'gold"."costs',
            },
        ),
        migrations.CreateModel(
            name="GoldIndicadoresMateriais",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("categoria", models.CharField(blank=True, max_length=100, null=True)),
                ("custo_total", models.FloatField(blank=True, null=True)),
                ("total_itens", models.BigIntegerField(blank=True, null=True)),
                ("custo_medio", models.FloatField(blank=True, null=True)),
                ("gold_updated_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": 'gold"."indicadores_materiais',
            },
        ),
    ]
