# Generated by Django 5.1.1 on 2026-05-11 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sca_data", "0005_gold_budget_snapshot"),
    ]

    operations = [
        migrations.AlterField(
            model_name="goldbudgetsnapshot",
            name="gerente_programa",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="goldbudgetsnapshot",
            name="nome_programa",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="goldbudgetsnapshot",
            name="nome_projeto",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="goldbudgetsnapshot",
            name="periodo",
            field=models.CharField(blank=True, default="", max_length=7),
        ),
        migrations.AlterField(
            model_name="goldbudgetsnapshot",
            name="responsavel_projeto",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="goldbudgetsnapshot",
            name="saude_financeira",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AlterField(
            model_name="goldbudgetsnapshot",
            name="status",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="goldcosts",
            name="gerente_programa",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="goldcosts",
            name="nome_programa",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="goldcosts",
            name="nome_projeto",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="goldcosts",
            name="responsavel_projeto",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="goldindicadoresmateriais",
            name="categoria",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="silverestoquemateriaisprojeto",
            name="localizacao",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="silverfornecedor",
            name="categoria",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="silverfornecedor",
            name="cidade",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="silverfornecedor",
            name="estado",
            field=models.CharField(blank=True, default="", max_length=2),
        ),
        migrations.AlterField(
            model_name="silverfornecedor",
            name="razao_social",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="silverfornecedor",
            name="status",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="silvermaterial",
            name="categoria",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="silvermaterial",
            name="descricao",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="silvermaterial",
            name="fabricante",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="silvermaterial",
            name="status",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="silverpedidocompra",
            name="status",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="silverprograma",
            name="gerente_programa",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="silverprograma",
            name="gerente_tecnico",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="silverprograma",
            name="status",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="silverprojeto",
            name="nome_projeto",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="silverprojeto",
            name="responsavel",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="silverprojeto",
            name="status",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="silversolicitacaocompra",
            name="prioridade",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="silversolicitacaocompra",
            name="status",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="silvertarefaprojeto",
            name="responsavel",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="silvertarefaprojeto",
            name="status",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="silvertarefaprojeto",
            name="titulo",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="silvertempotarefa",
            name="usuario",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
