# Generated by Django 5.1.1 on 2026-05-24 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sca_data", "0009_fatoexecucaocarga_erros_avisos"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="fatoexecucaocarga",
            options={},
        ),
        migrations.AlterField(
            model_name="fatoexecucaocarga",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
