# Generated by Django 5.2.14 on 2026-05-25 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sca_data", "0010_alter_fatoexecucaocarga_options_and_more"),
        ("sca_data", "0010_auditexecutionlog"),
    ]

    operations = []
