# Generated by Django 5.1.1 on 2026-05-25 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sca_data", "0010_auditexecutionlog"),
        ("sca_data", "0010_fatoexecucaocarga_tipo_processo"),
    ]

    operations = []
