input {
  file {
    path => "/app/logs/app.log"
    # Força a leitura do arquivo desde o início
    start_position => "beginning"
    sincedb_path => "/dev/null"
    # Identificador único para este input
    id => "django_logs_stream"
  }
}

filter {
  json {
    source => "message"
    target => "parsed"
    skip_on_invalid_json => true
  }

  if [parsed] {
    mutate {
      add_field => {
        "log_level"    => "%{[parsed][level]}"
        "django_event" => "%{[parsed][event]}" 
        "api_method"   => "%{[parsed][method]}"
        "api_path"     => "%{[parsed][path]}"
        "api_status"   => "%{[parsed][status]}"
        "timestamp_br" => "%{[parsed][time]}"
      }
    }

    mutate {
      remove_field => [ "event", "parsed", "message" ]
    }
  }
}

output {
  # Envia para o Elasticsearch
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "django-logs-%{+YYYY.MM.dd}"
    # Desativa o gerenciamento de ciclo de vida para evitar conflitos em dev
    ilm_enabled => false
  }
  # Para debug: Imprime os eventos processados no console do Logstash
  stdout { 
    codec => rubydebug 
  }
}