REQUIRED_COLUMNS: dict[str, set[str]] = {
    "programas": {
        "id",
        "codigo_programa",
        "nome_programa",
        "gerente_programa",
        "gerente_tecnico",
        "data_inicio",
        "data_fim_prevista",
        "status",
    },
    "projetos": {
        "id",
        "codigo_projeto",
        "nome_projeto",
        "programa_id",
        "responsavel",
        "custo_hora",
        "data_inicio",
        "data_fim_prevista",
        "status",
    },
    "materiais": {
        "id",
        "codigo_material",
        "descricao",
        "categoria",
        "fabricante",
        "custo_estimado",
        "status",
    },
    "empenho_materiais": {
        "id",
        "projeto_id",
        "material_id",
        "quantidade_empenhada",
        "data_empenho",
    },
    "estoque_materiais_projeto": {
        "id",
        "projeto_id",
        "material_id",
        "quantidade",
        "localizacao",
    },
    "fornecedores": {
        "id",
        "codigo_fornecedor",
        "razao_social",
        "cidade",
        "estado",
        "categoria",
        "status",
    },
    "pedidos_compra": {
        "id",
        "numero_pedido",
        "solicitacao_id",
        "fornecedor_id",
        "data_pedido",
        "data_previsao_entrega",
        "valor_total",
        "status",
    },
    "solicitacoes_compra": {
        "id",
        "numero_solicitacao",
        "projeto_id",
        "material_id",
        "quantidade",
        "data_solicitacao",
        "prioridade",
        "status",
    },
    "compras_projeto": {
        "id",
        "pedido_compra_id",
        "projeto_id",
        "valor_alocado",
    },
    "tarefas_projeto": {
        "id",
        "codigo_tarefa",
        "projeto_id",
        "titulo",
        "responsavel",
        "estimativa_horas",
        "data_inicio",
        "data_fim_prevista",
        "status",
    },
    "tempo_tarefas": {
        "id",
        "tarefa_id",
        "usuario",
        "data",
        "horas_trabalhadas",
    },
}
